// Generated by gen_content.py — DO NOT EDIT MANUALLY

/// File type information metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TypeInfo {
    pub label: &'static str,
    pub mime_type: &'static str,
    pub group: &'static str,
    pub description: &'static str,
    pub extensions: &'static [&'static str],
    pub is_text: bool,
}

pub const NUM_TARGET_LABELS: usize = 214;

/// 214 target labels recognized by the Magika neural network.
#[rustfmt::skip]
pub static TARGET_LABELS: [&str; NUM_TARGET_LABELS] = [
    "3gp",
    "ace",
    "ai",
    "aidl",
    "apk",
    "applebplist",
    "appleplist",
    "asm",
    "asp",
    "autohotkey",
    "autoit",
    "awk",
    "batch",
    "bazel",
    "bib",
    "bmp",
    "bzip",
    "c",
    "cab",
    "cat",
    "chm",
    "clojure",
    "cmake",
    "cobol",
    "coff",
    "coffeescript",
    "cpp",
    "crt",
    "crx",
    "cs",
    "csproj",
    "css",
    "csv",
    "dart",
    "deb",
    "dex",
    "dicom",
    "diff",
    "dm",
    "dmg",
    "doc",
    "dockerfile",
    "docx",
    "dsstore",
    "dwg",
    "dxf",
    "elf",
    "elixir",
    "emf",
    "eml",
    "epub",
    "erb",
    "erlang",
    "flac",
    "flv",
    "fortran",
    "gemfile",
    "gemspec",
    "gif",
    "gitattributes",
    "gitmodules",
    "go",
    "gradle",
    "groovy",
    "gzip",
    "h5",
    "handlebars",
    "haskell",
    "hcl",
    "hlp",
    "htaccess",
    "html",
    "icns",
    "ico",
    "ics",
    "ignorefile",
    "ini",
    "internetshortcut",
    "ipynb",
    "iso",
    "jar",
    "java",
    "javabytecode",
    "javascript",
    "jinja",
    "jp2",
    "jpeg",
    "json",
    "jsonl",
    "julia",
    "kotlin",
    "latex",
    "lha",
    "lisp",
    "lnk",
    "lua",
    "m3u",
    "m4",
    "macho",
    "makefile",
    "markdown",
    "matlab",
    "mht",
    "midi",
    "mkv",
    "mp3",
    "mp4",
    "mscompress",
    "msi",
    "mum",
    "npy",
    "npz",
    "nupkg",
    "objectivec",
    "ocaml",
    "odp",
    "ods",
    "odt",
    "ogg",
    "one",
    "onnx",
    "otf",
    "outlook",
    "parquet",
    "pascal",
    "pcap",
    "pdb",
    "pdf",
    "pebin",
    "pem",
    "perl",
    "php",
    "pickle",
    "png",
    "po",
    "postscript",
    "powershell",
    "ppt",
    "pptx",
    "prolog",
    "proteindb",
    "proto",
    "psd",
    "python",
    "pythonbytecode",
    "pytorch",
    "qt",
    "r",
    "randombytes",
    "randomtxt",
    "rar",
    "rdf",
    "rpm",
    "rst",
    "rtf",
    "ruby",
    "rust",
    "scala",
    "scss",
    "sevenzip",
    "sgml",
    "shell",
    "smali",
    "snap",
    "solidity",
    "sql",
    "sqlite",
    "squashfs",
    "srt",
    "stlbinary",
    "stltext",
    "sum",
    "svg",
    "swf",
    "swift",
    "tar",
    "tcl",
    "textproto",
    "tga",
    "thumbsdb",
    "tiff",
    "toml",
    "torrent",
    "tsv",
    "ttf",
    "twig",
    "txt",
    "typescript",
    "vba",
    "vcxproj",
    "verilog",
    "vhdl",
    "vtt",
    "vue",
    "wasm",
    "wav",
    "webm",
    "webp",
    "winregistry",
    "wmf",
    "woff",
    "woff2",
    "xar",
    "xls",
    "xlsb",
    "xlsx",
    "xml",
    "xpi",
    "xz",
    "yaml",
    "yara",
    "zig",
    "zip",
    "zlibstream",
];

/// Detection thresholds for each target label.
#[rustfmt::skip]
pub static THRESHOLDS: [f32; NUM_TARGET_LABELS] = [
    0.50, // 3gp
    0.50, // ace
    0.50, // ai
    0.50, // aidl
    0.50, // apk
    0.50, // applebplist
    0.50, // appleplist
    0.50, // asm
    0.50, // asp
    0.50, // autohotkey
    0.50, // autoit
    0.50, // awk
    0.50, // batch
    0.50, // bazel
    0.50, // bib
    0.50, // bmp
    0.50, // bzip
    0.50, // c
    0.50, // cab
    0.50, // cat
    0.50, // chm
    0.50, // clojure
    0.50, // cmake
    0.50, // cobol
    0.50, // coff
    0.50, // coffeescript
    0.50, // cpp
    0.90, // crt
    0.50, // crx
    0.50, // cs
    0.50, // csproj
    0.50, // css
    0.50, // csv
    0.50, // dart
    0.50, // deb
    0.50, // dex
    0.50, // dicom
    0.50, // diff
    0.50, // dm
    0.50, // dmg
    0.50, // doc
    0.50, // dockerfile
    0.50, // docx
    0.50, // dsstore
    0.50, // dwg
    0.50, // dxf
    0.50, // elf
    0.50, // elixir
    0.50, // emf
    0.50, // eml
    0.50, // epub
    0.50, // erb
    0.50, // erlang
    0.50, // flac
    0.50, // flv
    0.50, // fortran
    0.50, // gemfile
    0.50, // gemspec
    0.50, // gif
    0.50, // gitattributes
    0.50, // gitmodules
    0.50, // go
    0.50, // gradle
    0.50, // groovy
    0.50, // gzip
    0.50, // h5
    0.90, // handlebars
    0.50, // haskell
    0.50, // hcl
    0.50, // hlp
    0.50, // htaccess
    0.50, // html
    0.50, // icns
    0.50, // ico
    0.50, // ics
    0.95, // ignorefile
    0.50, // ini
    0.50, // internetshortcut
    0.50, // ipynb
    0.50, // iso
    0.50, // jar
    0.50, // java
    0.50, // javabytecode
    0.50, // javascript
    0.50, // jinja
    0.50, // jp2
    0.50, // jpeg
    0.50, // json
    0.50, // jsonl
    0.50, // julia
    0.50, // kotlin
    0.95, // latex
    0.50, // lha
    0.50, // lisp
    0.50, // lnk
    0.50, // lua
    0.50, // m3u
    0.50, // m4
    0.50, // macho
    0.50, // makefile
    0.75, // markdown
    0.50, // matlab
    0.50, // mht
    0.50, // midi
    0.50, // mkv
    0.50, // mp3
    0.50, // mp4
    0.50, // mscompress
    0.50, // msi
    0.50, // mum
    0.50, // npy
    0.50, // npz
    0.50, // nupkg
    0.50, // objectivec
    0.90, // ocaml
    0.50, // odp
    0.50, // ods
    0.50, // odt
    0.50, // ogg
    0.50, // one
    0.50, // onnx
    0.50, // otf
    0.50, // outlook
    0.50, // parquet
    0.95, // pascal
    0.50, // pcap
    0.50, // pdb
    0.50, // pdf
    0.50, // pebin
    0.50, // pem
    0.50, // perl
    0.50, // php
    0.50, // pickle
    0.50, // png
    0.50, // po
    0.50, // postscript
    0.50, // powershell
    0.50, // ppt
    0.50, // pptx
    0.50, // prolog
    0.50, // proteindb
    0.50, // proto
    0.50, // psd
    0.50, // python
    0.50, // pythonbytecode
    0.50, // pytorch
    0.50, // qt
    0.90, // r
    0.50, // randombytes
    0.50, // randomtxt
    0.50, // rar
    0.50, // rdf
    0.50, // rpm
    0.90, // rst
    0.50, // rtf
    0.50, // ruby
    0.50, // rust
    0.50, // scala
    0.50, // scss
    0.50, // sevenzip
    0.50, // sgml
    0.50, // shell
    0.50, // smali
    0.50, // snap
    0.50, // solidity
    0.90, // sql
    0.50, // sqlite
    0.50, // squashfs
    0.50, // srt
    0.50, // stlbinary
    0.50, // stltext
    0.50, // sum
    0.50, // svg
    0.50, // swf
    0.50, // swift
    0.50, // tar
    0.50, // tcl
    0.50, // textproto
    0.50, // tga
    0.50, // thumbsdb
    0.50, // tiff
    0.50, // toml
    0.50, // torrent
    0.90, // tsv
    0.50, // ttf
    0.50, // twig
    0.50, // txt
    0.50, // typescript
    0.50, // vba
    0.50, // vcxproj
    0.50, // verilog
    0.50, // vhdl
    0.50, // vtt
    0.50, // vue
    0.50, // wasm
    0.50, // wav
    0.50, // webm
    0.50, // webp
    0.50, // winregistry
    0.50, // wmf
    0.50, // woff
    0.50, // woff2
    0.50, // xar
    0.50, // xls
    0.50, // xlsb
    0.50, // xlsx
    0.50, // xml
    0.50, // xpi
    0.50, // xz
    0.50, // yaml
    0.50, // yara
    0.90, // zig
    0.50, // zip
    0.50, // zlibstream
];

/// Type info array indexed by target label index (0..214).
#[rustfmt::skip]
pub static TARGET_TYPE_INFOS: [TypeInfo; NUM_TARGET_LABELS] = [
    TypeInfo {
        label: "3gp",
        mime_type: "video/3gpp",
        group: "video",
        description: "3GPP multimedia file",
        extensions: &["3gp"],
        is_text: false,
    },
    TypeInfo {
        label: "ace",
        mime_type: "application/x-ace-compressed",
        group: "archive",
        description: "ACE archive",
        extensions: &["ace"],
        is_text: false,
    },
    TypeInfo {
        label: "ai",
        mime_type: "application/pdf",
        group: "document",
        description: "Adobe Illustrator Artwork",
        extensions: &["ai"],
        is_text: false,
    },
    TypeInfo {
        label: "aidl",
        mime_type: "text/plain",
        group: "unknown",
        description: "Android Interface Definition Language",
        extensions: &["aidl"],
        is_text: true,
    },
    TypeInfo {
        label: "apk",
        mime_type: "application/vnd.android.package-archive",
        group: "executable",
        description: "Android package",
        extensions: &["apk"],
        is_text: false,
    },
    TypeInfo {
        label: "applebplist",
        mime_type: "application/x-bplist",
        group: "application",
        description: "Apple binary property list",
        extensions: &["bplist", "plist"],
        is_text: false,
    },
    TypeInfo {
        label: "appleplist",
        mime_type: "application/x-plist",
        group: "application",
        description: "Apple property list",
        extensions: &["plist"],
        is_text: true,
    },
    TypeInfo {
        label: "asm",
        mime_type: "text/x-asm",
        group: "code",
        description: "Assembly",
        extensions: &["s", "S", "asm"],
        is_text: true,
    },
    TypeInfo {
        label: "asp",
        mime_type: "text/html",
        group: "code",
        description: "ASP source",
        extensions: &["aspx", "asp"],
        is_text: true,
    },
    TypeInfo {
        label: "autohotkey",
        mime_type: "text/plain",
        group: "code",
        description: "AutoHotKey script",
        extensions: &[],
        is_text: true,
    },
    TypeInfo {
        label: "autoit",
        mime_type: "text/plain",
        group: "code",
        description: "AutoIt script",
        extensions: &["au3"],
        is_text: true,
    },
    TypeInfo {
        label: "awk",
        mime_type: "text/plain",
        group: "code",
        description: "Awk",
        extensions: &["awk"],
        is_text: true,
    },
    TypeInfo {
        label: "batch",
        mime_type: "text/x-msdos-batch",
        group: "code",
        description: "DOS batch file",
        extensions: &["bat"],
        is_text: true,
    },
    TypeInfo {
        label: "bazel",
        mime_type: "text/plain",
        group: "code",
        description: "Bazel build file",
        extensions: &["bzl"],
        is_text: true,
    },
    TypeInfo {
        label: "bib",
        mime_type: "text/x-bibtex",
        group: "text",
        description: "BibTeX",
        extensions: &["bib"],
        is_text: true,
    },
    TypeInfo {
        label: "bmp",
        mime_type: "image/bmp",
        group: "image",
        description: "BMP image data",
        extensions: &["bmp"],
        is_text: false,
    },
    TypeInfo {
        label: "bzip",
        mime_type: "application/x-bzip2",
        group: "archive",
        description: "bzip2 compressed data",
        extensions: &["bz2", "tbz2", "tar.bz2"],
        is_text: false,
    },
    TypeInfo {
        label: "c",
        mime_type: "text/x-c",
        group: "code",
        description: "C source",
        extensions: &["c"],
        is_text: true,
    },
    TypeInfo {
        label: "cab",
        mime_type: "application/vnd.ms-cab-compressed",
        group: "archive",
        description: "Microsoft Cabinet archive data",
        extensions: &["cab"],
        is_text: false,
    },
    TypeInfo {
        label: "cat",
        mime_type: "application/octet-stream",
        group: "application",
        description: "Windows Catalog file",
        extensions: &["cat"],
        is_text: false,
    },
    TypeInfo {
        label: "chm",
        mime_type: "application/chm",
        group: "application",
        description: "MS Windows HtmlHelp Data",
        extensions: &["chm"],
        is_text: false,
    },
    TypeInfo {
        label: "clojure",
        mime_type: "text/x-clojure",
        group: "code",
        description: "Clojure",
        extensions: &["clj", "cljs", "cljc", "cljr"],
        is_text: true,
    },
    TypeInfo {
        label: "cmake",
        mime_type: "text/x-cmake",
        group: "code",
        description: "CMake build file",
        extensions: &["cmake"],
        is_text: true,
    },
    TypeInfo {
        label: "cobol",
        mime_type: "text/x-cobol",
        group: "code",
        description: "Cobol",
        extensions: &["cbl", "cob", "cpy", "CBL", "COB", "CPY"],
        is_text: true,
    },
    TypeInfo {
        label: "coff",
        mime_type: "application/x-coff",
        group: "executable",
        description: "Intel 80386 COFF",
        extensions: &["obj", "o"],
        is_text: false,
    },
    TypeInfo {
        label: "coffeescript",
        mime_type: "text/coffeescript",
        group: "code",
        description: "CoffeeScript",
        extensions: &["coffee"],
        is_text: true,
    },
    TypeInfo {
        label: "cpp",
        mime_type: "text/x-c",
        group: "code",
        description: "C++ source",
        extensions: &["cc", "cpp", "cxx", "c++", "cppm", "ixx"],
        is_text: true,
    },
    TypeInfo {
        label: "crt",
        mime_type: "application/x-x509-ca-cert",
        group: "text",
        description: "Certificates (binary format)",
        extensions: &["der", "cer", "crt"],
        is_text: false,
    },
    TypeInfo {
        label: "crx",
        mime_type: "application/x-chrome-extension",
        group: "executable",
        description: "Google Chrome extension",
        extensions: &["crx"],
        is_text: false,
    },
    TypeInfo {
        label: "cs",
        mime_type: "text/plain",
        group: "code",
        description: "C# source",
        extensions: &["cs", "csx"],
        is_text: true,
    },
    TypeInfo {
        label: "csproj",
        mime_type: "text/plain",
        group: "code",
        description: ".NET project config",
        extensions: &["csproj"],
        is_text: true,
    },
    TypeInfo {
        label: "css",
        mime_type: "text/css",
        group: "code",
        description: "CSS source",
        extensions: &["css"],
        is_text: true,
    },
    TypeInfo {
        label: "csv",
        mime_type: "text/csv",
        group: "code",
        description: "CSV document",
        extensions: &["csv"],
        is_text: true,
    },
    TypeInfo {
        label: "dart",
        mime_type: "text/plain",
        group: "code",
        description: "Dart source",
        extensions: &["dart"],
        is_text: true,
    },
    TypeInfo {
        label: "deb",
        mime_type: "application/vnd.debian.binary-package",
        group: "archive",
        description: "Debian binary package",
        extensions: &["deb"],
        is_text: false,
    },
    TypeInfo {
        label: "dex",
        mime_type: "application/x-android-dex",
        group: "executable",
        description: "Dalvik dex file",
        extensions: &["dex"],
        is_text: false,
    },
    TypeInfo {
        label: "dicom",
        mime_type: "application/dicom",
        group: "image",
        description: "DICOM",
        extensions: &["dcm"],
        is_text: false,
    },
    TypeInfo {
        label: "diff",
        mime_type: "text/plain",
        group: "text",
        description: "Diff file",
        extensions: &["diff", "patch"],
        is_text: true,
    },
    TypeInfo {
        label: "dm",
        mime_type: "text/plain",
        group: "code",
        description: "Dream Maker",
        extensions: &["dm"],
        is_text: true,
    },
    TypeInfo {
        label: "dmg",
        mime_type: "application/x-apple-diskimage",
        group: "archive",
        description: "Apple disk image",
        extensions: &["dmg"],
        is_text: false,
    },
    TypeInfo {
        label: "doc",
        mime_type: "application/msword",
        group: "document",
        description: "Microsoft Word CDF document",
        extensions: &["doc"],
        is_text: false,
    },
    TypeInfo {
        label: "dockerfile",
        mime_type: "text/x-dockerfile",
        group: "code",
        description: "Dockerfile",
        extensions: &[],
        is_text: true,
    },
    TypeInfo {
        label: "docx",
        mime_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        group: "document",
        description: "Microsoft Word 2007+ document",
        extensions: &["docx", "docm"],
        is_text: false,
    },
    TypeInfo {
        label: "dsstore",
        mime_type: "application/octet-stream",
        group: "unknown",
        description: "Application Desktop Services Store",
        extensions: &[],
        is_text: false,
    },
    TypeInfo {
        label: "dwg",
        mime_type: "image/x-dwg",
        group: "image",
        description: "Autocad Drawing",
        extensions: &["dwg"],
        is_text: false,
    },
    TypeInfo {
        label: "dxf",
        mime_type: "image/vnd.dxf",
        group: "image",
        description: "Audocad Drawing Exchange Format",
        extensions: &["dxf"],
        is_text: true,
    },
    TypeInfo {
        label: "elf",
        mime_type: "application/x-executable-elf",
        group: "executable",
        description: "ELF executable",
        extensions: &["elf"],
        is_text: false,
    },
    TypeInfo {
        label: "elixir",
        mime_type: "text/plain",
        group: "code",
        description: "Elixir script",
        extensions: &["exs"],
        is_text: true,
    },
    TypeInfo {
        label: "emf",
        mime_type: "application/octet-stream",
        group: "application",
        description: "Windows Enhanced Metafile image data",
        extensions: &["emf"],
        is_text: false,
    },
    TypeInfo {
        label: "eml",
        mime_type: "message/rfc822",
        group: "text",
        description: "RFC 822 mail",
        extensions: &["eml"],
        is_text: true,
    },
    TypeInfo {
        label: "epub",
        mime_type: "application/epub+zip",
        group: "document",
        description: "EPUB document",
        extensions: &["epub"],
        is_text: false,
    },
    TypeInfo {
        label: "erb",
        mime_type: "text/x-ruby",
        group: "code",
        description: "Embedded Ruby source",
        extensions: &["erb"],
        is_text: true,
    },
    TypeInfo {
        label: "erlang",
        mime_type: "text/x-erlang",
        group: "code",
        description: "Erlang source",
        extensions: &["erl", "hrl"],
        is_text: true,
    },
    TypeInfo {
        label: "flac",
        mime_type: "audio/flac",
        group: "audio",
        description: "FLAC audio bitstream data",
        extensions: &["flac"],
        is_text: false,
    },
    TypeInfo {
        label: "flv",
        mime_type: "video/x-flv",
        group: "video",
        description: "Flash Video",
        extensions: &["flv"],
        is_text: false,
    },
    TypeInfo {
        label: "fortran",
        mime_type: "text/x-fortran",
        group: "document",
        description: "Fortran",
        extensions: &["f90", "f95", "f03", "F90"],
        is_text: true,
    },
    TypeInfo {
        label: "gemfile",
        mime_type: "text/plain",
        group: "code",
        description: "Gemfile file",
        extensions: &[],
        is_text: true,
    },
    TypeInfo {
        label: "gemspec",
        mime_type: "text/plain",
        group: "code",
        description: "Gemspec file",
        extensions: &["gemspec"],
        is_text: true,
    },
    TypeInfo {
        label: "gif",
        mime_type: "image/gif",
        group: "image",
        description: "GIF image data",
        extensions: &["gif"],
        is_text: false,
    },
    TypeInfo {
        label: "gitattributes",
        mime_type: "text/plain",
        group: "code",
        description: "Gitattributes file",
        extensions: &[],
        is_text: true,
    },
    TypeInfo {
        label: "gitmodules",
        mime_type: "text/plain",
        group: "code",
        description: "Gitmodules file",
        extensions: &[],
        is_text: true,
    },
    TypeInfo {
        label: "go",
        mime_type: "text/x-golang",
        group: "code",
        description: "Golang source",
        extensions: &["go"],
        is_text: true,
    },
    TypeInfo {
        label: "gradle",
        mime_type: "text/x-groovy",
        group: "code",
        description: "Gradle source",
        extensions: &["gradle"],
        is_text: true,
    },
    TypeInfo {
        label: "groovy",
        mime_type: "text/x-groovy",
        group: "code",
        description: "Groovy source",
        extensions: &["groovy"],
        is_text: true,
    },
    TypeInfo {
        label: "gzip",
        mime_type: "application/gzip",
        group: "archive",
        description: "gzip compressed data",
        extensions: &["gz", "gzip", "tgz", "tar.gz"],
        is_text: false,
    },
    TypeInfo {
        label: "h5",
        mime_type: "application/x-hdf5",
        group: "archive",
        description: "Hierarchical Data Format v5",
        extensions: &["h5", "hdf5"],
        is_text: false,
    },
    TypeInfo {
        label: "handlebars",
        mime_type: "text/x-handlebars-template",
        group: "code",
        description: "Handlebars source",
        extensions: &["hbs", "handlebars"],
        is_text: true,
    },
    TypeInfo {
        label: "haskell",
        mime_type: "text/plain",
        group: "code",
        description: "Haskell source",
        extensions: &["hs", "lhs"],
        is_text: true,
    },
    TypeInfo {
        label: "hcl",
        mime_type: "text/x-hcl",
        group: "code",
        description: "HashiCorp configuration language",
        extensions: &["hcl"],
        is_text: true,
    },
    TypeInfo {
        label: "hlp",
        mime_type: "application/winhlp",
        group: "application",
        description: "MS Windows help",
        extensions: &["hlp"],
        is_text: false,
    },
    TypeInfo {
        label: "htaccess",
        mime_type: "text/x-apache-conf",
        group: "code",
        description: "Apache access configuration",
        extensions: &[],
        is_text: true,
    },
    TypeInfo {
        label: "html",
        mime_type: "text/html",
        group: "code",
        description: "HTML document",
        extensions: &["html", "htm", "xhtml", "xht"],
        is_text: true,
    },
    TypeInfo {
        label: "icns",
        mime_type: "image/x-icns",
        group: "image",
        description: "Mac OS X icon",
        extensions: &["icns"],
        is_text: false,
    },
    TypeInfo {
        label: "ico",
        mime_type: "image/vnd.microsoft.icon",
        group: "image",
        description: "MS Windows icon resource",
        extensions: &["ico"],
        is_text: false,
    },
    TypeInfo {
        label: "ics",
        mime_type: "text/calendar",
        group: "application",
        description: "Internet Calendaring and Scheduling",
        extensions: &["ics"],
        is_text: true,
    },
    TypeInfo {
        label: "ignorefile",
        mime_type: "text/plain",
        group: "code",
        description: "Ignorefile",
        extensions: &[],
        is_text: true,
    },
    TypeInfo {
        label: "ini",
        mime_type: "text/plain",
        group: "text",
        description: "INI configuration file",
        extensions: &["ini"],
        is_text: true,
    },
    TypeInfo {
        label: "internetshortcut",
        mime_type: "application/x-mswinurl",
        group: "application",
        description: "MS Windows Internet shortcut",
        extensions: &["url"],
        is_text: true,
    },
    TypeInfo {
        label: "ipynb",
        mime_type: "application/json",
        group: "code",
        description: "Jupyter notebook",
        extensions: &["ipynb"],
        is_text: true,
    },
    TypeInfo {
        label: "iso",
        mime_type: "application/x-iso9660-image",
        group: "archive",
        description: "ISO 9660 CD-ROM filesystem data",
        extensions: &["iso"],
        is_text: false,
    },
    TypeInfo {
        label: "jar",
        mime_type: "application/java-archive",
        group: "archive",
        description: "Java archive data (JAR)",
        extensions: &["jar", "klib"],
        is_text: false,
    },
    TypeInfo {
        label: "java",
        mime_type: "text/x-java",
        group: "code",
        description: "Java source",
        extensions: &["java"],
        is_text: true,
    },
    TypeInfo {
        label: "javabytecode",
        mime_type: "application/x-java-applet",
        group: "executable",
        description: "Java compiled bytecode",
        extensions: &["class"],
        is_text: false,
    },
    TypeInfo {
        label: "javascript",
        mime_type: "application/javascript",
        group: "code",
        description: "JavaScript source",
        extensions: &["js", "mjs", "cjs"],
        is_text: true,
    },
    TypeInfo {
        label: "jinja",
        mime_type: "text/x-jinja2-template",
        group: "code",
        description: "Jinja template",
        extensions: &["jinja", "jinja2", "j2"],
        is_text: true,
    },
    TypeInfo {
        label: "jp2",
        mime_type: "image/jpeg2000",
        group: "image",
        description: "jpeg2000",
        extensions: &["jp2"],
        is_text: false,
    },
    TypeInfo {
        label: "jpeg",
        mime_type: "image/jpeg",
        group: "image",
        description: "JPEG image data",
        extensions: &["jpg", "jpeg"],
        is_text: false,
    },
    TypeInfo {
        label: "json",
        mime_type: "application/json",
        group: "code",
        description: "JSON document",
        extensions: &["json"],
        is_text: true,
    },
    TypeInfo {
        label: "jsonl",
        mime_type: "application/json",
        group: "code",
        description: "JSONL document",
        extensions: &["jsonl", "jsonld"],
        is_text: true,
    },
    TypeInfo {
        label: "julia",
        mime_type: "text/x-julia",
        group: "code",
        description: "Julia source",
        extensions: &["jl"],
        is_text: true,
    },
    TypeInfo {
        label: "kotlin",
        mime_type: "text/plain",
        group: "code",
        description: "Kotlin source",
        extensions: &["kt", "kts"],
        is_text: true,
    },
    TypeInfo {
        label: "latex",
        mime_type: "text/x-tex",
        group: "text",
        description: "LaTeX document",
        extensions: &["tex", "sty"],
        is_text: true,
    },
    TypeInfo {
        label: "lha",
        mime_type: "application/x-lha",
        group: "archive",
        description: "LHarc archive",
        extensions: &["lha", "lzh"],
        is_text: false,
    },
    TypeInfo {
        label: "lisp",
        mime_type: "text/x-lisp",
        group: "code",
        description: "Lisp source",
        extensions: &["lisp", "lsp", "l", "cl"],
        is_text: true,
    },
    TypeInfo {
        label: "lnk",
        mime_type: "application/x-ms-shortcut",
        group: "application",
        description: "MS Windows shortcut",
        extensions: &["lnk"],
        is_text: false,
    },
    TypeInfo {
        label: "lua",
        mime_type: "text/plain",
        group: "code",
        description: "Lua",
        extensions: &["lua"],
        is_text: true,
    },
    TypeInfo {
        label: "m3u",
        mime_type: "text/plain",
        group: "application",
        description: "M3U playlist",
        extensions: &["m3u8", "m3u"],
        is_text: true,
    },
    TypeInfo {
        label: "m4",
        mime_type: "text/plain",
        group: "code",
        description: "GNU Macro",
        extensions: &["m4"],
        is_text: true,
    },
    TypeInfo {
        label: "macho",
        mime_type: "application/x-mach-o",
        group: "executable",
        description: "Mach-O executable",
        extensions: &[],
        is_text: false,
    },
    TypeInfo {
        label: "makefile",
        mime_type: "text/x-makefile",
        group: "code",
        description: "Makefile source",
        extensions: &[],
        is_text: true,
    },
    TypeInfo {
        label: "markdown",
        mime_type: "text/markdown",
        group: "text",
        description: "Markdown document",
        extensions: &["md", "markdown"],
        is_text: true,
    },
    TypeInfo {
        label: "matlab",
        mime_type: "text/x-matlab",
        group: "code",
        description: "Matlab Source",
        extensions: &["m", "matlab"],
        is_text: true,
    },
    TypeInfo {
        label: "mht",
        mime_type: "application/x-mimearchive",
        group: "code",
        description: "MHTML document",
        extensions: &["mht"],
        is_text: true,
    },
    TypeInfo {
        label: "midi",
        mime_type: "audio/midi",
        group: "audio",
        description: "Midi",
        extensions: &["mid"],
        is_text: false,
    },
    TypeInfo {
        label: "mkv",
        mime_type: "video/x-matroska",
        group: "video",
        description: "Matroska",
        extensions: &["mkv"],
        is_text: false,
    },
    TypeInfo {
        label: "mp3",
        mime_type: "audio/mpeg",
        group: "audio",
        description: "MP3 media file",
        extensions: &["mp3"],
        is_text: false,
    },
    TypeInfo {
        label: "mp4",
        mime_type: "video/mp4",
        group: "video",
        description: "MP4 media file",
        extensions: &["mp4"],
        is_text: false,
    },
    TypeInfo {
        label: "mscompress",
        mime_type: "application/x-ms-compress-szdd",
        group: "archive",
        description: "MS Compress archive data",
        extensions: &[],
        is_text: false,
    },
    TypeInfo {
        label: "msi",
        mime_type: "application/x-msi",
        group: "archive",
        description: "Microsoft Installer file",
        extensions: &["msi"],
        is_text: false,
    },
    TypeInfo {
        label: "mum",
        mime_type: "text/xml",
        group: "application",
        description: "Windows Update Package file",
        extensions: &["mum"],
        is_text: true,
    },
    TypeInfo {
        label: "npy",
        mime_type: "application/octet-stream",
        group: "archive",
        description: "Numpy Array",
        extensions: &["npy"],
        is_text: false,
    },
    TypeInfo {
        label: "npz",
        mime_type: "application/octet-stream",
        group: "archive",
        description: "Numpy Arrays Archive",
        extensions: &["npz"],
        is_text: false,
    },
    TypeInfo {
        label: "nupkg",
        mime_type: "application/octet-stream",
        group: "unknown",
        description: "NuGet Package",
        extensions: &["nupkg"],
        is_text: false,
    },
    TypeInfo {
        label: "objectivec",
        mime_type: "text/x-objcsrc",
        group: "code",
        description: "ObjectiveC source",
        extensions: &["m", "mm"],
        is_text: true,
    },
    TypeInfo {
        label: "ocaml",
        mime_type: "text-ocaml",
        group: "code",
        description: "OCaml",
        extensions: &["ml", "mli"],
        is_text: true,
    },
    TypeInfo {
        label: "odp",
        mime_type: "application/vnd.oasis.opendocument.presentation",
        group: "document",
        description: "OpenDocument Presentation",
        extensions: &["odp"],
        is_text: false,
    },
    TypeInfo {
        label: "ods",
        mime_type: "application/vnd.oasis.opendocument.spreadsheet",
        group: "document",
        description: "OpenDocument Spreadsheet",
        extensions: &["ods"],
        is_text: false,
    },
    TypeInfo {
        label: "odt",
        mime_type: "application/vnd.oasis.opendocument.text",
        group: "document",
        description: "OpenDocument Text",
        extensions: &["odt"],
        is_text: false,
    },
    TypeInfo {
        label: "ogg",
        mime_type: "audio/ogg",
        group: "audio",
        description: "Ogg data",
        extensions: &["ogg"],
        is_text: false,
    },
    TypeInfo {
        label: "one",
        mime_type: "application/msonenote",
        group: "document",
        description: "One Note",
        extensions: &["one"],
        is_text: false,
    },
    TypeInfo {
        label: "onnx",
        mime_type: "application/octet-stream",
        group: "archive",
        description: "Open Neural Network Exchange",
        extensions: &["onnx"],
        is_text: false,
    },
    TypeInfo {
        label: "otf",
        mime_type: "font/otf",
        group: "font",
        description: "OpenType font",
        extensions: &["otf"],
        is_text: false,
    },
    TypeInfo {
        label: "outlook",
        mime_type: "application/vnd.ms-outlook",
        group: "application",
        description: "MS Outlook Message",
        extensions: &[],
        is_text: false,
    },
    TypeInfo {
        label: "parquet",
        mime_type: "application/vnd.apache.parquet",
        group: "unknown",
        description: "Apache Parquet",
        extensions: &["pqt", "parquet"],
        is_text: false,
    },
    TypeInfo {
        label: "pascal",
        mime_type: "text/x-pascal",
        group: "code",
        description: "Pascal source",
        extensions: &["pas", "pp"],
        is_text: true,
    },
    TypeInfo {
        label: "pcap",
        mime_type: "application/vnd.tcpdump.pcap",
        group: "application",
        description: "pcap capture file",
        extensions: &["pcap", "pcapng"],
        is_text: false,
    },
    TypeInfo {
        label: "pdb",
        mime_type: "application/octet-stream",
        group: "application",
        description: "Windows Program Database",
        extensions: &["pdb"],
        is_text: false,
    },
    TypeInfo {
        label: "pdf",
        mime_type: "application/pdf",
        group: "document",
        description: "PDF document",
        extensions: &["pdf"],
        is_text: false,
    },
    TypeInfo {
        label: "pebin",
        mime_type: "application/x-dosexec",
        group: "executable",
        description: "PE Windows executable",
        extensions: &["exe", "dll"],
        is_text: false,
    },
    TypeInfo {
        label: "pem",
        mime_type: "application/x-pem-file",
        group: "application",
        description: "PEM certificate",
        extensions: &["pem", "pub", "gpg"],
        is_text: true,
    },
    TypeInfo {
        label: "perl",
        mime_type: "text/x-perl",
        group: "code",
        description: "Perl source",
        extensions: &["pl"],
        is_text: true,
    },
    TypeInfo {
        label: "php",
        mime_type: "text/x-php",
        group: "code",
        description: "PHP source",
        extensions: &["php"],
        is_text: true,
    },
    TypeInfo {
        label: "pickle",
        mime_type: "application/octet-stream",
        group: "application",
        description: "Python pickle",
        extensions: &["pickle", "pkl"],
        is_text: false,
    },
    TypeInfo {
        label: "png",
        mime_type: "image/png",
        group: "image",
        description: "PNG image",
        extensions: &["png"],
        is_text: false,
    },
    TypeInfo {
        label: "po",
        mime_type: "text/gettext-translation",
        group: "application",
        description: "Portable Object (PO) for i18n",
        extensions: &["po"],
        is_text: true,
    },
    TypeInfo {
        label: "postscript",
        mime_type: "application/postscript",
        group: "document",
        description: "PostScript document",
        extensions: &["ps"],
        is_text: false,
    },
    TypeInfo {
        label: "powershell",
        mime_type: "application/x-powershell",
        group: "code",
        description: "Powershell source",
        extensions: &["ps1"],
        is_text: true,
    },
    TypeInfo {
        label: "ppt",
        mime_type: "application/vnd.ms-powerpoint",
        group: "document",
        description: "Microsoft PowerPoint CDF document",
        extensions: &["ppt"],
        is_text: false,
    },
    TypeInfo {
        label: "pptx",
        mime_type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        group: "document",
        description: "Microsoft PowerPoint 2007+ document",
        extensions: &["pptx", "pptm"],
        is_text: false,
    },
    TypeInfo {
        label: "prolog",
        mime_type: "text/x-prolog",
        group: "code",
        description: "Prolog source",
        extensions: &["pl", "pro", "P"],
        is_text: true,
    },
    TypeInfo {
        label: "proteindb",
        mime_type: "application/octet-stream",
        group: "application",
        description: "Protein DB",
        extensions: &["pdb"],
        is_text: true,
    },
    TypeInfo {
        label: "proto",
        mime_type: "text/x-proto",
        group: "code",
        description: "Protocol buffer definition",
        extensions: &["proto"],
        is_text: true,
    },
    TypeInfo {
        label: "psd",
        mime_type: "image/vnd.adobe.photoshop",
        group: "image",
        description: "Adobe Photoshop",
        extensions: &["psd"],
        is_text: false,
    },
    TypeInfo {
        label: "python",
        mime_type: "text/x-python",
        group: "code",
        description: "Python source",
        extensions: &["py", "pyi"],
        is_text: true,
    },
    TypeInfo {
        label: "pythonbytecode",
        mime_type: "application/x-bytecode.python",
        group: "executable",
        description: "Python compiled bytecode",
        extensions: &["pyc", "pyo"],
        is_text: false,
    },
    TypeInfo {
        label: "pytorch",
        mime_type: "application/octet-stream",
        group: "application",
        description: "Pytorch storage file",
        extensions: &["pt", "pth"],
        is_text: false,
    },
    TypeInfo {
        label: "qt",
        mime_type: "video/quicktime",
        group: "video",
        description: "QuickTime",
        extensions: &["mov"],
        is_text: false,
    },
    TypeInfo {
        label: "r",
        mime_type: "text/x-R",
        group: "code",
        description: "R (language)",
        extensions: &["R"],
        is_text: true,
    },
    TypeInfo {
        label: "randombytes",
        mime_type: "application/octet-stream",
        group: "unknown",
        description: "Random bytes",
        extensions: &[],
        is_text: false,
    },
    TypeInfo {
        label: "randomtxt",
        mime_type: "text/plain",
        group: "text",
        description: "Random text",
        extensions: &[],
        is_text: true,
    },
    TypeInfo {
        label: "rar",
        mime_type: "application/vnd.rar",
        group: "archive",
        description: "RAR archive data",
        extensions: &["rar"],
        is_text: false,
    },
    TypeInfo {
        label: "rdf",
        mime_type: "application/rdf+xml",
        group: "text",
        description: "Resource Description Framework document (RDF)",
        extensions: &["rdf"],
        is_text: true,
    },
    TypeInfo {
        label: "rpm",
        mime_type: "application/x-rpm",
        group: "archive",
        description: "RedHat Package Manager archive (RPM)",
        extensions: &["rpm"],
        is_text: false,
    },
    TypeInfo {
        label: "rst",
        mime_type: "text/x-rst",
        group: "text",
        description: "ReStructuredText document",
        extensions: &["rst"],
        is_text: true,
    },
    TypeInfo {
        label: "rtf",
        mime_type: "text/rtf",
        group: "text",
        description: "Rich Text Format document",
        extensions: &["rtf"],
        is_text: true,
    },
    TypeInfo {
        label: "ruby",
        mime_type: "application/x-ruby",
        group: "code",
        description: "Ruby source",
        extensions: &["rb"],
        is_text: true,
    },
    TypeInfo {
        label: "rust",
        mime_type: "application/x-rust",
        group: "code",
        description: "Rust source",
        extensions: &["rs"],
        is_text: true,
    },
    TypeInfo {
        label: "scala",
        mime_type: "application/x-scala",
        group: "code",
        description: "Scala source",
        extensions: &["scala"],
        is_text: true,
    },
    TypeInfo {
        label: "scss",
        mime_type: "text/x-scss",
        group: "code",
        description: "SCSS source",
        extensions: &["scss"],
        is_text: true,
    },
    TypeInfo {
        label: "sevenzip",
        mime_type: "application/x-7z-compressed",
        group: "archive",
        description: "7-zip archive data",
        extensions: &["7z"],
        is_text: false,
    },
    TypeInfo {
        label: "sgml",
        mime_type: "application/sgml",
        group: "text",
        description: "sgml",
        extensions: &["sgml"],
        is_text: true,
    },
    TypeInfo {
        label: "shell",
        mime_type: "text/x-shellscript",
        group: "code",
        description: "Shell script",
        extensions: &["sh"],
        is_text: true,
    },
    TypeInfo {
        label: "smali",
        mime_type: "application/x-smali",
        group: "code",
        description: "Smali source",
        extensions: &["smali"],
        is_text: true,
    },
    TypeInfo {
        label: "snap",
        mime_type: "application/octet-stream",
        group: "archive",
        description: "Snap archive",
        extensions: &["snap"],
        is_text: false,
    },
    TypeInfo {
        label: "solidity",
        mime_type: "text/plain",
        group: "code",
        description: "Solidity source",
        extensions: &["sol"],
        is_text: true,
    },
    TypeInfo {
        label: "sql",
        mime_type: "application/x-sql",
        group: "code",
        description: "SQL source",
        extensions: &["sql"],
        is_text: true,
    },
    TypeInfo {
        label: "sqlite",
        mime_type: "application/octet-stream",
        group: "application",
        description: "SQLITE database",
        extensions: &["sqlite", "sqlite3"],
        is_text: false,
    },
    TypeInfo {
        label: "squashfs",
        mime_type: "application/octet-stream",
        group: "archive",
        description: "Squash filesystem",
        extensions: &[],
        is_text: false,
    },
    TypeInfo {
        label: "srt",
        mime_type: "text/srt",
        group: "application",
        description: "SubRip Text Format",
        extensions: &["srt"],
        is_text: true,
    },
    TypeInfo {
        label: "stlbinary",
        mime_type: "application/sla",
        group: "image",
        description: "Stereolithography CAD (binary)",
        extensions: &["stl"],
        is_text: false,
    },
    TypeInfo {
        label: "stltext",
        mime_type: "application/sla",
        group: "image",
        description: "Stereolithography CAD (text)",
        extensions: &["stl"],
        is_text: true,
    },
    TypeInfo {
        label: "sum",
        mime_type: "text/plain",
        group: "application",
        description: "Checksum file",
        extensions: &["sum"],
        is_text: true,
    },
    TypeInfo {
        label: "svg",
        mime_type: "image/svg+xml",
        group: "image",
        description: "SVG Scalable Vector Graphics image data",
        extensions: &["svg"],
        is_text: true,
    },
    TypeInfo {
        label: "swf",
        mime_type: "application/x-shockwave-flash",
        group: "executable",
        description: "Small Web File",
        extensions: &["swf"],
        is_text: false,
    },
    TypeInfo {
        label: "swift",
        mime_type: "text/x-swift",
        group: "code",
        description: "Swift",
        extensions: &["swift"],
        is_text: true,
    },
    TypeInfo {
        label: "tar",
        mime_type: "application/x-tar",
        group: "archive",
        description: "POSIX tar archive",
        extensions: &["tar"],
        is_text: false,
    },
    TypeInfo {
        label: "tcl",
        mime_type: "application/x-tcl",
        group: "code",
        description: "Tickle",
        extensions: &["tcl"],
        is_text: true,
    },
    TypeInfo {
        label: "textproto",
        mime_type: "text/plain",
        group: "code",
        description: "Text protocol buffer",
        extensions: &["textproto", "textpb", "pbtxt"],
        is_text: true,
    },
    TypeInfo {
        label: "tga",
        mime_type: "image/x-tga",
        group: "image",
        description: "Targa image data",
        extensions: &["tga"],
        is_text: false,
    },
    TypeInfo {
        label: "thumbsdb",
        mime_type: "image/vnd.ms-thumb",
        group: "application",
        description: "Windows thumbnail cache",
        extensions: &[],
        is_text: false,
    },
    TypeInfo {
        label: "tiff",
        mime_type: "image/tiff",
        group: "image",
        description: "TIFF image data",
        extensions: &["tiff", "tif"],
        is_text: false,
    },
    TypeInfo {
        label: "toml",
        mime_type: "application/toml",
        group: "text",
        description: "Tom's obvious, minimal language",
        extensions: &["toml"],
        is_text: true,
    },
    TypeInfo {
        label: "torrent",
        mime_type: "application/x-bittorrent",
        group: "application",
        description: "BitTorrent file",
        extensions: &["torrent"],
        is_text: false,
    },
    TypeInfo {
        label: "tsv",
        mime_type: "text/tsv",
        group: "code",
        description: "TSV document",
        extensions: &["tsv"],
        is_text: true,
    },
    TypeInfo {
        label: "ttf",
        mime_type: "font/sfnt",
        group: "font",
        description: "TrueType Font data",
        extensions: &["ttf", "ttc"],
        is_text: false,
    },
    TypeInfo {
        label: "twig",
        mime_type: "text/x-twig",
        group: "code",
        description: "Twig template",
        extensions: &["twig"],
        is_text: true,
    },
    TypeInfo {
        label: "txt",
        mime_type: "text/plain",
        group: "text",
        description: "Generic text document",
        extensions: &["txt"],
        is_text: true,
    },
    TypeInfo {
        label: "typescript",
        mime_type: "application/typescript",
        group: "code",
        description: "TypeScript source",
        extensions: &["ts", "mts", "cts"],
        is_text: true,
    },
    TypeInfo {
        label: "vba",
        mime_type: "text/vbscript",
        group: "code",
        description: "MS Visual Basic source (VBA)",
        extensions: &["vbs", "vba", "vb"],
        is_text: true,
    },
    TypeInfo {
        label: "vcxproj",
        mime_type: "application/xml",
        group: "code",
        description: "Visual Studio MSBuild project",
        extensions: &["vcxproj"],
        is_text: true,
    },
    TypeInfo {
        label: "verilog",
        mime_type: "text/x-verilog",
        group: "code",
        description: "Verilog source",
        extensions: &["v", "verilog", "vlg", "vh"],
        is_text: true,
    },
    TypeInfo {
        label: "vhdl",
        mime_type: "text/x-vhdl",
        group: "code",
        description: "VHDL source",
        extensions: &["vhd"],
        is_text: true,
    },
    TypeInfo {
        label: "vtt",
        mime_type: "text/vtt",
        group: "text",
        description: "Web Video Text Tracks",
        extensions: &["vtt", "webvtt"],
        is_text: true,
    },
    TypeInfo {
        label: "vue",
        mime_type: "application/javascript",
        group: "code",
        description: "Vue source",
        extensions: &["vue"],
        is_text: true,
    },
    TypeInfo {
        label: "wasm",
        mime_type: "application/wasm",
        group: "executable",
        description: "Web Assembly",
        extensions: &["wasm"],
        is_text: false,
    },
    TypeInfo {
        label: "wav",
        mime_type: "audio/x-wav",
        group: "audio",
        description: "Waveform Audio file (WAV)",
        extensions: &["wav"],
        is_text: false,
    },
    TypeInfo {
        label: "webm",
        mime_type: "video/webm",
        group: "video",
        description: "WebM media file",
        extensions: &["webm"],
        is_text: false,
    },
    TypeInfo {
        label: "webp",
        mime_type: "image/webp",
        group: "image",
        description: "WebP media file",
        extensions: &["webp"],
        is_text: false,
    },
    TypeInfo {
        label: "winregistry",
        mime_type: "text/x-ms-regedit",
        group: "application",
        description: "Windows Registry text",
        extensions: &["reg"],
        is_text: true,
    },
    TypeInfo {
        label: "wmf",
        mime_type: "image/wmf",
        group: "image",
        description: "Windows metafile",
        extensions: &["wmf"],
        is_text: false,
    },
    TypeInfo {
        label: "woff",
        mime_type: "font/woff",
        group: "font",
        description: "Web Open Font Format",
        extensions: &["woff"],
        is_text: false,
    },
    TypeInfo {
        label: "woff2",
        mime_type: "font/woff2",
        group: "font",
        description: "Web Open Font Format v2",
        extensions: &["woff2"],
        is_text: false,
    },
    TypeInfo {
        label: "xar",
        mime_type: "application/x-xar",
        group: "archive",
        description: "XAR archive compressed data",
        extensions: &["pkg", "xar"],
        is_text: false,
    },
    TypeInfo {
        label: "xls",
        mime_type: "application/vnd.ms-excel",
        group: "document",
        description: "Microsoft Excel CDF document",
        extensions: &["xls"],
        is_text: false,
    },
    TypeInfo {
        label: "xlsb",
        mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        group: "document",
        description: "Microsoft Excel 2007+ document (binary format)",
        extensions: &["xlsb"],
        is_text: false,
    },
    TypeInfo {
        label: "xlsx",
        mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        group: "document",
        description: "Microsoft Excel 2007+ document",
        extensions: &["xlsx", "xlsm"],
        is_text: false,
    },
    TypeInfo {
        label: "xml",
        mime_type: "text/xml",
        group: "code",
        description: "XML document",
        extensions: &["xml"],
        is_text: true,
    },
    TypeInfo {
        label: "xpi",
        mime_type: "application/zip",
        group: "archive",
        description: "Compressed installation archive (XPI)",
        extensions: &["xpi"],
        is_text: false,
    },
    TypeInfo {
        label: "xz",
        mime_type: "application/x-xz",
        group: "archive",
        description: "XZ compressed data",
        extensions: &["xz"],
        is_text: false,
    },
    TypeInfo {
        label: "yaml",
        mime_type: "application/x-yaml",
        group: "code",
        description: "YAML source",
        extensions: &["yml", "yaml"],
        is_text: true,
    },
    TypeInfo {
        label: "yara",
        mime_type: "text/x-yara",
        group: "code",
        description: "YARA rule",
        extensions: &["yar", "yara"],
        is_text: true,
    },
    TypeInfo {
        label: "zig",
        mime_type: "text/zig",
        group: "code",
        description: "Zig source",
        extensions: &["zig"],
        is_text: true,
    },
    TypeInfo {
        label: "zip",
        mime_type: "application/zip",
        group: "archive",
        description: "Zip archive data",
        extensions: &["zip"],
        is_text: false,
    },
    TypeInfo {
        label: "zlibstream",
        mime_type: "application/zlib",
        group: "application",
        description: "zlib compressed data",
        extensions: &[],
        is_text: false,
    },
];

pub static EMPTY_INFO: TypeInfo = TypeInfo { label: "empty", mime_type: "inode/x-empty", group: "inode", description: "Empty file", extensions: &[], is_text: false };
pub static UNKNOWN_INFO: TypeInfo = TypeInfo { label: "unknown", mime_type: "application/octet-stream", group: "unknown", description: "Unknown binary data", extensions: &[], is_text: false };
pub static UNDEFINED_INFO: TypeInfo = TypeInfo { label: "undefined", mime_type: "application/octet-stream", group: "unknown", description: "Undefined content type", extensions: &[], is_text: false };
pub static DIRECTORY_INFO: TypeInfo = TypeInfo { label: "directory", mime_type: "inode/directory", group: "inode", description: "A directory", extensions: &[], is_text: false };
pub static SYMLINK_INFO: TypeInfo = TypeInfo { label: "symlink", mime_type: "inode/symlink", group: "inode", description: "A symbolic link", extensions: &[], is_text: false };
pub static TXT_INFO: TypeInfo = TypeInfo { label: "txt", mime_type: "text/plain", group: "text", description: "Generic text document", extensions: &["txt"], is_text: true };

/// Returns overwrite label for a target label if defined (e.g. randombytes -> unknown, randomtxt -> txt).
pub fn get_overwrite_label(target_idx: usize) -> Option<&'static str> {
    match target_idx {
        148 => Some("unknown"), // randombytes -> unknown
        149 => Some("txt"), // randomtxt -> txt
        _ => None,
    }
}

/// Finds target label index by label name.
pub fn find_target_label_idx(label: &str) -> Option<usize> {
    TARGET_LABELS.iter().position(|&l| l == label)
}

/// Gets TypeInfo by label string.
pub fn get_type_info_by_label(label: &str) -> &'static TypeInfo {
    match label {
        "empty" => &EMPTY_INFO,
        "unknown" => &UNKNOWN_INFO,
        "undefined" => &UNDEFINED_INFO,
        "directory" => &DIRECTORY_INFO,
        "symlink" => &SYMLINK_INFO,
        "txt" => &TXT_INFO,
        _ => {
            if let Some(idx) = find_target_label_idx(label) {
                &TARGET_TYPE_INFOS[idx]
            } else {
                &UNKNOWN_INFO
            }
        }
    }
}
