//! Regenerate `src/vectors_data.rs` — the pinned cross-target fixture.
//!
//! ```text
//! cargo run -p katgpt-device-verify --features std --example gen_vectors \
//!   > crates/katgpt-device-verify/src/vectors_data.rs
//! ```
//!
//! Committed for provenance. A fixture whose derivation is not reproducible is
//! a blob of magic bytes, and the first time it disagrees with an
//! implementation nobody can tell which side is wrong. Every seed here is
//! `BLAKE3(label)` over a short ASCII label printed next to it.
//!
//! The fallback-branch vectors are **searched for**, not sampled: for a
//! `sides` value with a small residue the rejection branch is taken ~0.4% of
//! the time, so a random table exercises it never and a drifting fallback
//! ships green. The double-rejection set is searched harder still — both
//! leading bytes rejected **and** the v1 outcome different from v2 — so a
//! silent regression to v1's unconditional fallback flips every one of them.

use katgpt_device_verify::fair_roll::FairRollVerifier;
use katgpt_device_verify::merkle_verify::{EMPTY_HASH, compute_root_from_proof, hash_pair};

type Hash = [u8; 32];

fn seed_of(label: &str) -> Hash {
    *blake3::hash(label.as_bytes()).as_bytes()
}

fn hex(h: &Hash) -> String {
    h.iter().map(|b| format!("{b:#04x}, ")).collect()
}

fn emit(name: &str, doc: &str, rows: &[(String, Hash, u8, u8)]) {
    println!("/// {doc}");
    println!("pub const {name}: &[FairRollVector] = &[");
    for (label, seed, sides, die) in rows {
        println!("    FairRollVector {{");
        println!("        label: {label:?},");
        println!("        seed: [{}],", hex(seed).trim_end());
        println!("        sides: {sides},");
        println!("        die: {die},");
        println!("    }},");
    }
    println!("];");
}

/// `256 % sides` as the code computes it, so the search agrees with the roll.
fn threshold(sides: u8) -> u16 {
    256u16 - (256 % u16::from(sides))
}

fn main() {
    println!("// @generated by `examples/gen_vectors.rs` — DO NOT EDIT BY HAND.");
    println!("// Regenerate: cargo run -p katgpt-device-verify --features std \\");
    println!("//               --example gen_vectors > src/vectors_data.rs");
    println!();

    // ── Fair roll: sides that divide 256 (threshold == 256, fallback dead) ──
    let dividing: Vec<_> = [1u8, 2, 4, 8, 16, 32, 64, 128]
        .iter()
        .map(|&sides| {
            let label = format!("katgpt-device-verify/fair_roll/v2/div/{sides}");
            let seed = seed_of(&label);
            let die = FairRollVerifier::from_combined_seed(seed).roll_die(sides);
            (label, seed, sides, die)
        })
        .collect();
    emit(
        "FAIR_ROLL_DIVIDING_VECTORS",
        "Fair-roll vectors on `sides` values that divide 256 — \
         `threshold == 256`, so the first byte is always accepted and the \
         rejection branch is unreachable. These pin the common path.",
        &dividing,
    );
    println!();

    // ── Fair roll: sides that do NOT divide 256 (rejection branch is live) ──
    let nondividing: Vec<_> = [3u8, 5, 6, 7, 10, 12, 20, 100, 255]
        .iter()
        .map(|&sides| {
            let label = format!("katgpt-device-verify/fair_roll/v2/nondiv/{sides}");
            let seed = seed_of(&label);
            let die = FairRollVerifier::from_combined_seed(seed).roll_die(sides);
            (label, seed, sides, die)
        })
        .collect();
    emit(
        "FAIR_ROLL_NONDIVIDING_VECTORS",
        "Fair-roll vectors on `sides` values that do NOT divide 256 — the \
         rejection branch is live. This is where two well-meaning \
         implementations can reasonably differ, so this is where drift hides.",
        &nondividing,
    );
    println!();

    // ── Fair roll: seeds SEARCHED so that hash[0] >= threshold ──
    // Guarantees the first byte rejects, so a later byte decides the outcome.
    let fallback: Vec<_> = [3u8, 5, 6, 7, 10, 12, 20, 100, 255]
        .iter()
        .map(|&sides| {
            let t = threshold(sides);
            let (label, seed) = (0u32..)
                .map(|i| {
                    let l = format!("katgpt-device-verify/fair_roll/v2/fallback/{sides}/{i}");
                    let s = seed_of(&l);
                    (l, s)
                })
                .find(|(_, s)| u16::from(blake3::hash(s).as_bytes()[0]) >= t)
                .expect("a fallback-hitting seed exists for every sides > 0");
            let die = FairRollVerifier::from_combined_seed(seed).roll_die(sides);
            (label, seed, sides, die)
        })
        .collect();
    emit(
        "FAIR_ROLL_FALLBACK_VECTORS",
        "Fair-roll vectors whose seed was **searched** so that \
         `hash[0] >= threshold` — the first byte rejects, so the byte that \
         decides the outcome is a later one, by construction rather than \
         luck. Without these the branch is taken ~0.4% of the time for \
         `sides = 3` and a drifting rejection rule ships green.",
        &fallback,
    );
    println!();

    // ── Fair roll: seeds SEARCHED so hash[0] AND hash[1] both reject, with
    // v1 ≠ v2 outcomes — the v2 retry path, and a genuine v1/v2
    // discriminator per vector. This is the branch where v2 diverged from
    // v1's unconditional fallback byte, and where a silent regression back
    // to v1 changes the settled outcome.
    let dbltrej: Vec<_> = [3u8, 5, 6, 7, 10, 12, 20, 100, 255]
        .iter()
        .map(|&sides| {
            let t = threshold(sides);
            let (label, seed) = (0u32..)
                .map(|i| {
                    let l = format!("katgpt-device-verify/fair_roll/v2/dblrej/{sides}/{i}");
                    let s = seed_of(&l);
                    (l, s)
                })
                .find(|(_, s)| {
                    let h = blake3::hash(s);
                    let b = h.as_bytes();
                    u16::from(b[0]) >= t
                        && u16::from(b[1]) >= t
                        // v1 would deal b[1] % sides + 1 unconditionally;
                        // require it to DIFFER from the v2 outcome so every
                        // vector in this set discriminates the two seams.
                        && b[1] % sides + 1
                            != FairRollVerifier::from_combined_seed(*s).roll_die(sides)
                })
                .expect("a discriminating double-rejection seed exists for every sides > 0");
            let die = FairRollVerifier::from_combined_seed(seed).roll_die(sides);
            (label, seed, sides, die)
        })
        .collect();
    emit(
        "FAIR_ROLL_DOUBLE_REJECT_VECTORS",
        "Fair-roll vectors whose seed was **searched** so that `hash[0]` AND \
         `hash[1]` both meet the threshold AND the v1 outcome (unconditional \
         `hash[1] % sides + 1`) differs from the v2 one — the retry path \
         (deciding byte at index >= 2) is exercised by construction, and \
         every vector here flips if the implementation regresses to v1's \
         unconditional fallback.",
        &dbltrej,
    );
    println!();

    // ── Merkle: build small binary trees bottom-up, emit one proof each ──
    println!(
        "/// Merkle inclusion vectors — leaf + index + sibling path + root, \
         over binary trees of 1, 2, 3, 5, and 8 leaves. The odd counts \
         (3, 5) are the ones that exercise the promote-the-orphan level \
         layout; a power-of-two-only table proves nothing about them."
    );
    println!("pub const MERKLE_VECTORS: &[MerkleVector] = &[");
    for n_leaves in [1usize, 2, 3, 5, 8] {
        let leaves: Vec<Hash> = (0..n_leaves)
            .map(|i| {
                seed_of(&format!(
                    "katgpt-device-verify/merkle/v1/{n_leaves}/leaf{i}"
                ))
            })
            .collect();
        for index in 0..n_leaves {
            let (siblings, root) = proof_for(&leaves, index);
            let label = format!("n={n_leaves},i={index}");
            // Self-check: the emitted row must verify before it is pinned.
            assert_eq!(
                compute_root_from_proof(&leaves[index], index, &siblings),
                root,
                "generator emitted a non-verifying row for {label}"
            );
            println!("    MerkleVector {{");
            println!("        label: {label:?},");
            println!("        leaf: [{}],", hex(&leaves[index]).trim_end());
            println!("        index: {index},");
            print!("        siblings: &[");
            for s in &siblings {
                print!("[{}], ", hex(s).trim_end());
            }
            println!("],");
            println!("        root: [{}],", hex(&root).trim_end());
            println!("    }},");
        }
    }
    println!("];");
}

/// Build a binary Merkle tree bottom-up and return `(siblings, root)`.
///
/// An odd level's last node pairs with [`EMPTY_HASH`] — it is **not** promoted
/// unchanged. That is the rule `riir_neuron_db::merkle::MerkleTree` uses in
/// both `build_bottom_up` and `proof`, and the two conventions produce
/// different roots for every tree with an odd level. Getting this wrong is the
/// exact silent drift the fixture exists to catch, so it is spelled out rather
/// than inherited.
///
/// Re-derived here instead of importing the tree: the fixture is only worth
/// something as an *independent* witness. If this rule and the tree ever
/// disagree, the cross-repo assertion is what says so.
fn proof_for(leaves: &[Hash], index: usize) -> (Vec<Hash>, Hash) {
    // A single-leaf tree has an empty proof and the leaf as its root.
    if leaves.len() <= 1 {
        return (Vec::new(), leaves[0]);
    }

    let mut level: Vec<Hash> = leaves.to_vec();
    let mut idx = index;
    let mut siblings = Vec::new();

    while level.len() > 1 {
        let sibling_idx = idx ^ 1;
        siblings.push(if sibling_idx < level.len() {
            level[sibling_idx]
        } else {
            EMPTY_HASH
        });
        let mut next = Vec::with_capacity(level.len().div_ceil(2));
        let mut i = 0;
        while i < level.len() {
            next.push(if i + 1 < level.len() {
                hash_pair(&level[i], &level[i + 1])
            } else {
                hash_pair(&level[i], &EMPTY_HASH)
            });
            i += 2;
        }
        level = next;
        idx >>= 1;
    }
    (siblings, level[0])
}
